title: MattiaCardelli
baseURL: /
params:
  description: I'm_Mattia
  layout_style: overflow
  palette: blue
  favicon: ''
taxonomies:
  stub: stub
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true
