title: MattiaCardelli
baseURL: /
params:
  description: I'm_Mattia
  layout_style: overflow
  palette: blue
  footer:
    type: footer
    template: footer
    content: M. Cardelli. All_rights_reserved.
    links: []
  favicon: ''
taxonomies:
  stub: stub
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true
